### ISSUE TITLE
ModuleNotFoundError when running on Odoo.sh

### ISSUE THREAD

**Issue by zachwaite** [lmignon/extendable-pydantic#3]
I've added OCA/rest-framework as a submodule in our Odoo.sh environment and am using `base_rest_pydantic` successfully, but this traceback keeps showing up in the logs when starting a python interpreter or upgrading a module from the CLI. It appears to be coming from the fact that python hasn't fully loaded all the search paths at this point in the startup when the `.pth` is executed.

```
Error processing line 1 of /home/odoo/.local/lib/python3.8/site-packages/extendable_pydantic_patcher.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.8/site.py", line 175, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/home/odoo/.local/lib/python3.8/site-packages/extendable_pydantic/_patch.py", line 2, in <module>
      import wrapt
  ModuleNotFoundError: No module named 'wrapt'

Remainder of file ignored
Error processing line 1 of /home/odoo/.local/lib/python3.8/site-packages/extendable_pydantic_patcher.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.8/site.py", line 175, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/home/odoo/.local/lib/python3.8/site-packages/extendable_pydantic/_patch.py", line 2, in <module>
      import wrapt
  ModuleNotFoundError: No module named 'wrapt'
```

I edited `_patch.py` to add a call to `site.main()` before `import wrap` and it solves the error. Can provide a PR if useful. 

Thanks for your work on all this.

**Comment by damdam-s** [comment]
Can you please provide a PR for this fix? 
It will be useful while a fix from maintainer is elaborated.
